### ISSUE TITLE
Necessary Matlab Libraries

### ISSUE THREAD

**Issue by jbgadasi** [MHKiT-Software/MHKiT-MATLAB#107]
Hello,

Do you know what Matlab libraries/add-ons are required to use the full functionality of the Matlab version of MHKiT? I saw that a minimum of Matlab 2019b is required, but are there any additional requirements?

Thank you.

**Comment by rpauly18** [comment]
Hi, 

Thank you for reaching out. There are no other Matlab library dependancies. MHKiT-Matlab does currently have a dependency on MHKiT-Python, which requires Python v3.7 or higher and has some other Python packages that will be installed when you install MHKiT-Python.
