### ISSUE TITLE
Request WPTO fails with `omni-directional_wave_height`

### ISSUE THREAD

**Issue by simmsa** [MHKiT-Software/MHKiT-MATLAB#142]
Specific issue is here: https://github.com/MHKiT-Software/MHKiT-MATLAB/blob/e780f1c13680d74d22c68be092634c3da5d1e527/mhkit/wave/IO/hindcast/request_wpto.m#L117-L118

Anticipated fix is to remove dashes from parameter(z):

```{matlab}
sanitized_parameter = strrep(parameter(z), '-', "_");
data(y).(sanitized_parameter) = param.value;
```

**Comment by rpauly18** [comment]
resolved in #144
