### ISSUE TITLE
CDiP IO Functions 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-MATLAB#58]
Develop CDiP IO and graphics functions that match https://github.com/MHKiT-Software/MHKiT-Python/pull/72

**Comment by Matthew-Boyd** [comment]
@rpauly18  Are you still wanting all the code written in MATLAB now instead of wrapping Python code when we can (i.e., /wave/io/cdip.py) ?

**Comment by rpauly18** [comment]
> @rpauly18 Are you still wanting all the code written in MATLAB now instead of wrapping Python code when we can (i.e., /wave/io/cdip.py) ?

Yes, if it looks like it will be possible within a reasonable amount of time.
