### ISSUE TITLE
Tidal ebb and flood plots 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-MATLAB#65]
Matlab version of https://github.com/MHKiT-Software/MHKiT-Python/pull/125

**Comment by rpauly18** [comment]
To-Do - remove python dependency from plot functions

**Comment by simmsa** [comment]
Addressed in #108 

* Tidal [phase exceedance plottting](https://github.com/MHKiT-Software/MHKiT-MATLAB/blob/21453d1b4ad7f8712efd3f8e5c484ca1db486ca2/mhkit/tidal/graphics/plot_tidal_phase_exceedance.m)
* Tidal [phase probablity plotting](https://github.com/MHKiT-Software/MHKiT-MATLAB/blob/21453d1b4ad7f8712efd3f8e5c484ca1db486ca2/mhkit/tidal/graphics/plot_tidal_phase_probability.m)

Working example can be found in the [tidal module example](https://github.com/MHKiT-Software/MHKiT-MATLAB/blob/21453d1b4ad7f8712efd3f8e5c484ca1db486ca2/examples/tidal_example.html)

TODO:

* [ ] Update MHKiT documentation to include latest MHKiT-MATLAB notebooks
