### ISSUE TITLE
Run a Code Compatibility Report

### ISSUE THREAD

**Issue by Matthew-Boyd** [MHKiT-Software/MHKiT-MATLAB#67]
See this [link](https://www.mathworks.com/matlabcentral/answers/364764-is-there-a-tool-to-check-for-compatibility-between-different-matlab-versions).

Update main.yml and README with found compatible versions.

**Comment by simmsa** [comment]
This issue was addressed in #112 where we added code compatibility report to our GitHub Actions workflow. Results can be viewed [here](https://github.com/MHKiT-Software/MHKiT-MATLAB/actions/workflows/code_compatibility_report.yml).
