### ISSUE TITLE
1st Time user error log

### ISSUE THREAD

**Issue by pwobyrne** [MHKiT-Software/MHKiT-MATLAB#77]
Matlab 2021b
Python 3.9

running runTest for 1st time

I just wanted to pass along the results.  I have not tried to troubleshoot myself because I am a new user of the MHKit

[test_results.pdf](https://github.com/MHKiT-Software/MHKiT-MATLAB/files/7864758/test_results.pdf)

**Comment by rpauly18** [comment]
Thank you for your interest in MHKiT-Matlab. Can you tell me the version of MHKiT-Python you have installed by running 'py.help("mhkit")' from your Matlab terminal?

**Comment by pwobyrne** [comment]
[image: image.png]

Thanks for the quick response.  My name is Patrick OByrne and I am a
Graduate Student UNH working on our Tidal Energy Conversion platform (
https://livingbridge.unh.edu/).

My project is funded through NREL and we are working on preparing our data
that we collected this Fall to include in the TETHYS database.

Thank you,

- Pat

**Comment by rpauly18** [comment]
Hi Pat, 

Aidan has mentioned you were working with our team. Glad to hear you plan to use MHKiT. 

I can see that you attached an image, but it is not showing up for me. Can you send the version number via comment?

**Comment by pwobyrne** [comment]
v 0.4.0 i believe

**Comment by rpauly18** [comment]
We currently are working on a bug fix that I hope will solve most of these errors. (https://github.com/MHKiT-Software/MHKiT-MATLAB/pull/78) . I will let you know when these fixes have been merged so you can update your MHKiT package and try again. Thanks you!

**Comment by rpauly18** [comment]
@pwobyrne the changes that should resolve this issue have been merged into the repo. Please download the latest version of MHKiT-Matlab from the Git repo and re-install. Also make sure you are using MHKIT-Python that you pip installed, not a version downloaded from the repo. Let me know if any issues continue.

**Comment by simmsa** [comment]
@pwobyrne Thanks for helping troubleshoot this! The failing tests outlined in the initial test report are fixed by #108.
